### PR TITLE
Fixed issue with missing coverageAggregate.

### PR DESCRIPTION
**Pull request by jeffmay**
@audax-shreyaspurohit @mingy711 @macmacbr @danstaley

This should fix the coveralls errors.

### CODE REVIEW

**Comment by audax-shreyaspurohit** [comment]
lgtm though you could move it to the same sbt line instead of reloading it again which takes more time

**Comment by jeffmay** [comment]
@audax-shreyaspurohit unfortunately, this is what the instructions say:
https://github.com/scoverage/sbt-scoverage#multi-project-reports

> (Note, you must do this after all the coverage data is complete as a separate command, so you cannot do sbt coverage test coverageAggregate (at least until a way around this is found).)

**Comment by jeffmay** [comment]
Looks like it generated the report: https://coveralls.io/jobs/11897544

**Comment by audax-shreyaspurohit** [comment]
:+1:

**Pull request merged**
